stages:
  - build
  - code-style
  - testing
  - deploy
  - telegram

build_job:
  stage: build
  script:
    - echo "Starting build job"
    - cd src/Simple_Bash && make build
  after_script:
    - echo "Build job is completed"
    - chmod +x src/tg_bot.sh && bash src/tg_bot.sh "$CI_JOB_NAME" "$CI_JOB_STATUS"
  artifacts:
    expire_in: 30 days
    paths:
      - src/Simple_Bash/cat/s21_cat
      - src/Simple_Bash/grep/s21_grep 

code-style_job:
  stage: code-style
  script:
    - echo "Starting code-style test job"
    - cd src/Simple_Bash && make clang
  after_script:     
    - echo "Code-style test job is completed"
    - chmod +x src/tg_bot.sh && bash src/tg_bot.sh "$CI_JOB_NAME" "$CI_JOB_STATUS"

testing_job:
  stage: testing
  allow_failure: false
  script:
    - echo "Starting testing job"
    - cd src/Simple_Bash && make test
  after_script:
    - echo "Testing job is completed"
    - chmod +x src/tg_bot.sh && bash src/tg_bot.sh "$CI_JOB_NAME" "$CI_JOB_STATUS" 
  when: on_success 

deploy_job:
  stage: deploy
  allow_failure: false
  script:
    - echo "Starting deploy job"
    - chmod +x src/deployment.sh
    - bash src/deployment.sh
  after_script:
    - echo "Deploy job is completed"
    - chmod +x src/tg_bot.sh && bash src/tg_bot.sh "$CI_JOB_NAME" "$CI_JOB_STATUS"
  when: manual

tg_success_job:
  stage: telegram
  script:
    - chmod +x src/tg_bot.sh && bash src/tg_bot.sh "CI/CD Pipeline $CI_PIPELINE_ID" "Passed"
  when: on_success

tg_failure_job:
  stage: telegram
  script:
    - chmod +x src/tg_bot.sh && bash src/tg_bot.sh "CI/CD Pipeline $CI_PIPELINE_ID" "Failed"
  when: on_failure
