error_log   /var/log/nginx/error.log notice;

events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;
        server_name localhost;

        location / {
            proxy_pass http://fcgiserver:81;
        }
    }
}
